version: '3.1'

services:
  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
    depends_on:
      - mongo
    healthcheck:
      test:
        [
          'CMD',
          'mongo',
          '--quiet',
          '127.0.0.1/test',
          '--eval',
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .env:/app/.env
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 1234:1234
